name: 'AI FaillogLens'
description: 'AI that zooms into your failure logs and tells you exactly what broke'
author: 'Sathish'

branding:
  icon: 'search'
  color: 'red'

inputs:
  github-token:
    description: 'GitHub token for posting PR comments and GitHub Models AI'
    required: true
    default: ${{ github.token }}
  post-comment:
    description: 'Post analysis as a PR comment'
    required: false
    default: 'true'
  post-summary:
    description: 'Post analysis as a job summary'
    required: false
    default: 'true'
  failed-job-name:
    description: 'Name of the failed job to analyze (optional)'
    required: false
    default: ''
  remote-patterns-url:
    description: 'URL to fetch additional community patterns from'
    required: false
    default: ''
  enable-ai:
    description: 'Use GitHub Models AI as fallback when no pattern matches (uses your GITHUB_TOKEN — no extra API key needed)'
    required: false
    default: 'true'

outputs:
  root-cause:
    description: 'Plain-English root cause of the failure'
  failed-step:
    description: 'The step that caused the failure'
  suggestion:
    description: 'Suggested fix for the failure'
  matched-pattern:
    description: 'ID of the pattern that matched (or ai-generated / none)'
  category:
    description: 'Category of the failure'
  ai-generated:
    description: 'Whether the suggestion was AI-generated (true/false)'

runs:
  using: 'node20'
  main: 'dist/index.js'
