import { FailureAnalysis } from './analyzer'

const SEVERITY_EMOJI = {
  critical: '🔴',
  warning: '🟡',
  info: '🔵'
}

const SEVERITY_LABEL = {
  critical: 'Critical',
  warning: 'Warning',
  info: 'Info'
}

export function formatPRComment(analysis: FailureAnalysis, jobName: string, runUrl: string): string {
  const emoji = SEVERITY_EMOJI[analysis.severity]
  const label = SEVERITY_LABEL[analysis.severity]

  const exactMatchBlock = analysis.exactMatchLine
    ? `\n### 🎯 Exact Error Line ${analysis.exactMatchLineNumber > 0 ? `*(line ${analysis.exactMatchLineNumber} of ${analysis.totalLines})*` : ''}
\`\`\`
${analysis.exactMatchLine}
\`\`\``
    : ''

  const errorBlock = analysis.errorLines.length > 0
    ? `\n<details>\n<summary>📋 All error lines detected (${analysis.errorLines.length})</summary>\n\n\`\`\`\n${analysis.errorLines.join('\n')}\n\`\`\`\n</details>`
    : ''

  const aiNote = analysis.aiGenerated
    ? `\n> 🤖 *This analysis was generated by GitHub Models AI*\n`
    : ''

  return `## ${emoji} AI FaillogLens — Failure Analysis

> **Job:** \`${jobName}\` · **Severity:** ${label} · **Scanned:** ${analysis.totalLines} log lines · [View full logs](${runUrl})

---

### 🔍 Root Cause
${analysis.rootCause}
${aiNote}
### 📍 Failed Step
\`${analysis.failedStep}\`
${exactMatchBlock}

### 💡 Suggested Fix
${analysis.suggestion}
${errorBlock}

---
<sub>🔬 Analyzed by [AI FaillogLens](https://github.com/SKCloudOps/ai-faillog-lens) · [Report false positive](https://github.com/SKCloudOps/ai-faillog-lens/issues)</sub>`
}

export function formatJobSummary(
  analysis: FailureAnalysis,
  jobName: string,
  runUrl: string,
  steps: { name: string; conclusion: string | null; started_at?: string | null; completed_at?: string | null }[],
  triggeredBy: string,
  branch: string,
  commit: string,
  repo: string
): string {
  const emoji = SEVERITY_EMOJI[analysis.severity]
  const label = SEVERITY_LABEL[analysis.severity]
  const now = new Date().toUTCString()

  // Step breakdown
  const stepRows = steps.map(step => {
    const icon =
      step.conclusion === 'success' ? '✅' :
      step.conclusion === 'failure' ? '❌' :
      step.conclusion === 'skipped' ? '⏭️' :
      step.conclusion === 'cancelled' ? '🚫' : '⏳'

    const duration = step.started_at && step.completed_at
      ? `${Math.round((new Date(step.completed_at).getTime() - new Date(step.started_at).getTime()) / 1000)}s`
      : '—'

    const isFailedStep = step.name === analysis.failedStep
      ? ' ← **failure here**'
      : ''

    return `| ${icon} | \`${step.name}\` | ${step.conclusion ?? 'in progress'} | ${duration} |${isFailedStep}`
  }).join('\n')

  // Top 10 error lines only in summary
  const topErrorLines = analysis.errorLines
    .slice(0, 10)
    .join('\n')

  const aiNote = analysis.aiGenerated
    ? `> 🤖 This suggestion was generated by **GitHub Models AI** (confidence: see suggestion)\n\n`
    : `> 🎯 Matched pattern: \`${analysis.matchedPattern}\` · Category: \`${analysis.category}\`\n\n`

  return `# ${emoji} AI FaillogLens — Failure Report

---

## 📊 Run Overview

| | |
|---|---|
| **Repository** | \`${repo}\` |
| **Branch** | \`${branch}\` |
| **Commit** | [\`${commit.substring(0, 7)}\`](https://github.com/${repo}/commit/${commit}) |
| **Triggered By** | \`${triggeredBy}\` |
| **Job** | \`${jobName}\` |
| **Severity** | ${emoji} ${label} |
| **Log Lines Scanned** | ${analysis.totalLines.toLocaleString()} lines |
| **Analyzed At** | ${now} |
| **Full Logs** | [View on GitHub Actions ↗](${runUrl}) |

---

## 🔍 Root Cause

> ### ${analysis.rootCause}

${aiNote}

---

## 🎯 Exact Error

${analysis.exactMatchLineNumber > 0
  ? `Found on **line ${analysis.exactMatchLineNumber}** of ${analysis.totalLines.toLocaleString()}:`
  : 'Top error line detected:'}

\`\`\`
${analysis.exactMatchLine || 'No exact match found'}
\`\`\`

---

## 💡 Suggested Fix

${analysis.suggestion}

---

## 🗂️ Step Breakdown

| Status | Step | Result | Duration |
|---|---|---|---|
${stepRows}

---

## 📋 Error Lines (top 10 of ${analysis.errorLines.length})

\`\`\`
${topErrorLines || 'No error lines captured'}
\`\`\`

---

## 🛠️ Quick Actions

| Action | Link |
|---|---|
| 🔗 View full workflow run | [Open ↗](${runUrl}) |
| 📋 Add custom pattern | [patterns.json ↗](https://github.com/${repo}/blob/main/patterns.json) |
| 🐛 Report false positive | [Open issue ↗](https://github.com/SKCloudOps/ai-faillog-lens/issues) |
| 📖 Documentation | [README ↗](https://github.com/SKCloudOps/ai-faillog-lens#readme) |

---

<sub>🔬 Analyzed by <a href="https://github.com/SKCloudOps/ai-faillog-lens">AI FaillogLens</a> · ${now}</sub>`
}
